### ISSUE TITLE
dart2js doesn't work anymore with mustache

### ISSUE THREAD

**Issue by sircco** [valotas/mustache4dart#62] opened 2017-06-01 12:43 UTC
var salut = compile('Hello {{name}}!');
print(salut({'name': 'Alice'})); //should print Hello Alice!

i recently upgraded from 1.0.10 to 1.1.0 where all worked fine.
Simple example above doesnt work anymore with pub serve in chrome, but works in dartium. I guess its something related to mirrors?

**Comment by valotas** [comment] 2017-06-03 15:01
How exactly are you using the library? Do you have a public repo that I can have a look? 

There are some changes regarding mirrors yes and if you have the problem only on transpiled code, it should have to do with that, but I have to reproduce the problem first.

**Comment by sircco** [comment] 2017-06-03 18:14
we use it in our dev so i thought that something is wrong with our environment so i 
created  just plain stagehand simple web project, latest mustache as single dep.

main.dart that consists of coypasted lines above
linux 64 bit ubuntu
Dart VM version: 1.23.0 (Fri Apr 21 10:05:24 2017) on "linux_x64"  

dart2js, also tried ddc, no luck but works in dartium.

when i reverted back to mustache4dart 1.0.10 it all works fine again

**Comment by valotas** [comment] 2017-06-03 21:34
Ok, I reproduced the problem. I'll have a look at it asap

**Comment by valotas** [comment] 2017-06-04 17:04
Can you try to run your app with `-DMIRRORS=false` ?

**Comment by sircco** [comment] 2017-06-05 06:32
looks like it works that way

**Comment by valotas** [comment] 2017-06-12 19:07
It looks like dartjs can not handle all cases with reflection. I'm reworking the context computations on #64 and I hope some of the problems will go aways. If you do not have any other problem I'll close this

**Comment by sircco** [comment] 2017-06-12 19:41
we are already running latest git version in production so its safe to say that we have no problems currently

**Comment by valotas** [comment] 2017-06-12 19:51
what do you mean latest git version? Master is (most of the time) in sync with pub. If you want, you can try branch `issue62/dart2js` where I did some changes to the mirrors implementation. In any case, if you run with `-DMIRRORS=false` you do not use that part at all.

**Comment by sircco** [comment] 2017-06-13 09:54
using in pubspec
 mustache4dart:   
   git: https://github.com/valotas/mustache4dart.git   
with -DMIRRORS=false
because pub doesn't have strong mode compliancy yet

**Closed** 2017-06-13 19:16 UTC
